### ISSUE TITLE
Disparo no funciona a cierta distancia

### ISSUE THREAD

**Issue by sheilajulvez** [Proyectos1-FDI-UCM/c2022-Grupo07#101]
### Descripción
Al estar situado algo alejado de un enemigo y realizar el disparo no afecta a este último.

### Pasos:
1.Situarse a cierta distancia alejada del enemigo
2.Efectuar el disparo
3.Observar como la bala se destruye, pero el enemigo se queda tal cual.

### Capturas de Pantalla:
![image](https://user-images.githubusercontent.com/100275159/165826294-d25898df-cc28-4e7c-a2b7-72a599e87195.png)

**Comment by PabloGonzalezArroyoo** [comment]
Hola Sheila,

El comportamiento esperado de la bala es que, tras 2 segundos, se destruya sola (típico LifeTimeController de motores) para que no exista la posibilidad de que haya muchas balas instanciadas a la vez. Entonces, no sabemos si lo que nos comentas aquí es algo intencionado o si verdaderamente la bala colisiona, se destruye por ello y no funciona. 

¿Podrías aclararnos lo, por favor?
