### ISSUE TITLE
Fallo con la ralentización del tiempo en el Boss

### ISSUE THREAD

**Issue by CiscoGalvan** [Proyectos1-FDI-UCM/c2022-Grupo07#87]
### Pasos 
1.Llegamos a las pruebas del boss.
2.Justo antes de caer al suelo, pulsamos K+N
3.Veremos que todo el juego irá a cámara lenta y de ninguna manera ese efecto se puede revertir (a no ser que volvamos al jefe y continuemos a la batalla en sí).

### Captura de pantalla o vídeo
Enlace al video que lo demuestra: [![Texto alternativo](https://img.youtube.com/vi/SIhoGb5ILYw/0.jpg)](https://youtu.be/SIhoGb5ILYw)

**Comment by PabloGonzalezArroyoo** [comment]
Resuelto.
