### ISSUE TITLE
Error en el Menú y Game Over(ERROR CRÍTICO)

### ISSUE THREAD

**Issue by JoseMorenob** [Proyectos1-FDI-UCM/c2022-Grupo07#89]
### Al perder por falta de tiempo, es decir, el contador llega a 0 y aparece el menú de derrota, este no funciona en un principio, ningún botón funciona durante un rato, pero las animaciones de transición de menús siguen funcionando. Al pasar unos momentos y presionar el botón Menú sí te lleva al Menú principal pero cuando le das a play vuelve la partida con el estado anterior que tenía, con la pantalla de derrota por tiempo, pero sin el menú de Game Over.

Imposibilita continuar la partida, si 	En este estado  se pulsa el menú de pausa y se intenta volver a jugar seguirá sin funcionar el juego, ocurrirán los de antes y los textos del menú están superpuestos. En el modo debug ocurre lo mismo.

### Pasos 

1. Perder por falta de tiempo o en cualquier momento puede ocurrir.
2. Presionar el botón de Menú (no funcionará).
3. Al rato sí te dejará y te levará al main menú.
4. Presionar play.
### Captura de pantalla 
![unnamed (4)](https://user-images.githubusercontent.com/100274773/165495143-c0bed189-9607-49dc-ad0e-889a90a91558.png)
![unnamed (3)](https://user-images.githubusercontent.com/100274773/165495147-aae88a15-76a0-4792-a1f1-ec995a27f31c.png)
![unnamed (2)](https://user-images.githubusercontent.com/100274773/165495149-a2d48d3e-e489-4584-b582-d90253349304.png)

**Comment by PabloGonzalezArroyoo** [comment]
Resuelto
