### ISSUE TITLE
Botones GameOver no funcionan

### ISSUE THREAD

**Issue by sheilajulvez** [Proyectos1-FDI-UCM/c2022-Grupo07#96]
### Descripción
Cuando te quedas sin vida y aparece el menú de Game Over, el botón Retry y a veces el de menú no funciona.

### Pasos 

Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.

1-Morir en el nivel normal, en el menú de pruebas,etc
2-Pulsar el botón Retry, (con el space o click)
3-Observar como no funciona y te mantiene en el mismo menú de GameOver

### Captura de pantalla o vídeo

![unnamed](https://user-images.githubusercontent.com/100275159/165821642-24a18ace-3cc7-4e8b-b6d8-c49381302754.png)

**Comment by PabloGonzalezArroyoo** [comment]
Resuelto
