### ISSUE TITLE
Error Game Over por tiempo

### ISSUE THREAD

**Issue by CristinaMora** [Proyectos1-FDI-UCM/c2022-Grupo07#97]
El error detectado consiste en la aparición del menú de GameOver por tiempo cuando aún el jugador dispone de este.
He tratado de reproducir el error, pero no he sido capaz. 
Adjunto la captura del error:
![segetg](https://user-images.githubusercontent.com/100274708/165823307-b258bb18-f1f5-4b3e-b5c5-5503c1c34a41.png)

**Comment by PabloGonzalezArroyoo** [comment]
Resuelto
