### ISSUE TITLE
La cuenta atrás sigue disminuyendo estando en los distintos menús

### ISSUE THREAD

**Issue by sheilajulvez** [Proyectos1-FDI-UCM/c2022-Grupo07#98]
### Descripción
La cuenta atrás sigue disminuyendo estando en el menú.

### Pasos 

1.Situarse en cualquier menú.
2.Observar el contador de tiempo.
3. cuando llegue a cero te salta el mensaje de TIME! y te pone que has perdido

### Captura de pantalla o vídeo

![image](https://user-images.githubusercontent.com/100275159/165822437-7da0436d-fa58-44ae-b010-8d1cea44740c.png)
![image](https://user-images.githubusercontent.com/100275159/165824647-af210e77-7cf7-46c6-a13f-1bb57e20e713.png)

**Comment by PabloGonzalezArroyoo** [comment]
Resuelto
